baseURL = "http://libgeos.org/"
languageCode = "en-us"
title = "GEOS"
theme = "hugo-geekdoc"
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true
enableGitInfo = true

[params]
  current_release = "3.9.1"
  geekdocLogo = "web-logo.png"
  # turn these on when we move to the main branch
  #geekdocRepo = "https://github.com/libgeos/geos"
  #geekdocEditPath = "web"
  geekdocBackToTop = true
